export {
  ADMIN_PERMISSIONS,
  ADMIN_ROLES,
  ADMIN_SCOPE_TYPES,
  type AdminAuthorizationContext,
  type AdminMembershipScope,
  type AdminPermission,
  type AdminRole,
  type AdminScopeType,
  type AuthorizationDecision,
  authorizeAdminAction,
  isResourceWithinScope,
  type ResourceScope,
  roleHasPermission,
  roleRequiresMfa,
} from "./admin-rbac.js";
